### ISSUE TITLE
OSX client stops working on screen sleep or system sleep

### ISSUE THREAD

**Issue by dkorunic** [swift/swift#102]
OSX client version 4.0 release stops sending/receiving XMPP messages as soon as screen sleeps or system sleeps on macOS 10.13.*. It's not possible to recover from this without restarting the client.

**Comment by Kev** [comment]
Thanks for the report. Could you check that clicking the status widget (the green egg), changing that to grey and back to green doesn't fix it, please?

macOS has started sleeping more agressively recently, which kills Swift's network connection. In my experience it does recover after a brief spell on wakeup, though.

**Comment by dkorunic** [comment]
Stopped using Jabber all together, we can safely close this due to inactivity :)
