### ISSUE TITLE
How could I build swiften only ?

### ISSUE THREAD

**Issue by pengweichu** [swift/swift#104]
How could I build swiften only ? For both Windows and Linux.

**Comment by sdfg2** [comment]
I'd like to know this too, given it's all I need for spectrum2 on a headless server.

**Comment by vitalyster** [comment]
basically `./scons Swiften` builds only Swiften

**Comment by sdfg2** [comment]
@vitalyster And that won't need all the qt deps?

**Comment by vitalyster** [comment]
@sdfg2 No, swiften does not use Qt

**Comment by Kev** [comment]
Offhand, I think it should be the same as Swift, but without Qt.

**Comment by sdfg2** [comment]
If I want to install it to the system, would I just use the same line as in the readme?

`./scons SWIFT_INSTALLDIR=/usr/local /usr/local`

Or do I need something else?
