### ISSUE TITLE
[Feature] HTTP-Upload

### ISSUE THREAD

**Issue by DoM1niC** [swift/swift#11]
Hey Swift looks like real awesome.... I currently use Conversation as Client by Android, a HTTP Upload Feature will real awesome to share under Windows Files to my Android Clients.

Watch 4 https://github.com/siacs/HttpUploadComponent

**Comment by Kev** [comment]
Thanks. This isn't on the immediate roadmap, but how to do file sharing via MUC (or MIXs) is something we're interested in, and may well involve HTTP Upload in the future.

**Comment by LNJ2** [comment]
I would also love to see this feature :+1:
