### ISSUE TITLE
swift-im build failure due to deprecated Boost.Signal

### ISSUE THREAD

**Issue by jubalh** [swift/swift#110]
Currently swift 4.0 does not build for us at [openSUSE](https://build.opensuse.org/package/show/network/swift-im) anymore because libboost-signal was removed.
I think boost moved from signal to signal2 quite [some time ago](https://www.boost.org/users/history/version_1_54_0.html): `Signals: No longer actively maintained, so it is deprecated. Use Signals2 for new development`.

**Comment by vitalyster** [comment]
swift 4 does not need libboost-signal, you can safely remove that dependency from build scrips (signals2 is header-only library)

**Comment by jubalh** [comment]
Right I realized it shortly after opening this issue. Sorry guys :)
