### ISSUE TITLE
Bundles vulnerable copy of Expat - please update to 2.2.7

### ISSUE THREAD

**Issue by hartwork** [swift/swift#114]
Hi!

This repository [bundles an outdated vulnerable copy of Expat 2.2.1](https://github.com/swift/swift/blob/2bb40b14d3d7f5cebc56601dad066d5201040bd2/3rdParty/Expat/src/expat.h#L1052). Please update your copy to version 2.2.7 with the latest security fixes. A change log with details is available at https://github.com/libexpat/libexpat/blob/master/expat/Changes . Thank you!

Best

&nbsp;
Sebastian

CC #70

**Comment by hartwork** [comment]
Any news?

**Comment by tfar** [comment]
Thanks for the hint. I see that I get version 2.2.7 in the repo this week.

**Comment by hartwork** [comment]
Cool, thank you!

**Comment by hartwork** [comment]
Any news?

**Comment by Kev** [comment]
Hi. Yes, this has been merged, thanks for the heads-up.

**Comment by hartwork** [comment]
Cool, thank you!
