### ISSUE TITLE
XML StreamError (Swift::ClientError::Type) on <footag> in element content.

### ISSUE THREAD

**Issue by geobra** [swift/swift#115]
A little code snipped to reproduce this error.

----------------------------------- 8< --------------------------------------
        Swift::Message::ref msg(new Swift::Message);
        Swift::IDGenerator idGenerator;
        std::string msgId = idGenerator.generateID();
        Swift::JID toJID = Swift::JID(jid.toStdString());

        msg->setFrom(Swift::JID(client_->getJID()));
        msg->setID(msgId);

        QString displayedPayload = "<displayed xmlns='" +  chatMarkersIdentifier + "' id='" + displayedMsgId + "' ";

        if (itsAMuc == true)
        {
            msg->setTo(toJID.toBare());
            msg->setType(Swift::Message::Groupchat);

            QString sender = QString::fromStdString(toJID.toString());

            if (toJID.isBare() == true)
            {
                sender += "/" + persistence_->getResourceForMsgId(displayedMsgId);
            }

            displayedPayload += " sender='" +  sender + "'";
        }
        else
        {
            msg->setTo(toJID);
            msg->setType(Swift::Message::Normal);
        }

        displayedPayload += " />";

        msg->addPayload(boost::make_shared<Swift::RawXMLPayload>(displayedPayload.toStdString()));

        client_->sendMessage(msg);
----------------------------------- 8< --------------------------------------

Assume displayedPayload contains:
<displayed xmlns="urn:xmpp:chat-markers:0" id="abc" sender="3q1u5zjubr4rb@conference.jabber.ccc.de/123<xyz>456"></displayed>

This causes Swiften to exit with 'StreamError'. If I programmatically replace the '123<xyz>456' by '123(xyz)456', all works fine. I would assume that <> inside of a content element within the " did not get interpreted by Swithen library.

**Comment by Kev** [comment]
The stream error is coming from the server being unhappy with what's sent, which implies that the stanza you're crafting is invalid somehow, probably invalid XML. This is quite likely to happen, I'd suggest creating payloads and the appropriate parsers/serialisers, rather than relying on hand-crafting XML. The RawXMLPayload is exactly as it sounds - this is the raw XML that's going to be written to the stream, the user is responsible for ensuring that it's valid.

**Comment by geobra** [comment]
Thank you for clarifying this. I use a qt xmlwriter class now and it works like a charm.
