### ISSUE TITLE
Chat History

### ISSUE THREAD

**Issue by anthonymetzler** [swift/swift#119]
Is there anyway to recover chat history? If so, where is it stored when using the Windows app?

**Comment by Kev** [comment]
Hi Anthony. Swift doesn't store the chat history locally. In the future it'll allow access to the server-side (MAM) history storage, but at the moment you'd have to query the server through another mechanism.

**Comment by VA1DER** [comment]
Has there been any movement on getting Swift to access the server side chat history?

If not, can we re-open this?
