### ISSUE TITLE
[Feature] nativ Emoji Support

### ISSUE THREAD

**Issue by DoM1niC** [swift/swift#13]
Hey Guys,

A real optional Feature will to add native Emoji 4 Work with mobile Clients like Android/iOS and so on...

http://emojione.com/

**Comment by Kev** [comment]
Thanks for this suggestion. As far as I've seen, mobile clients sending Emoji to Swift works ok already, doesn't it?

**Comment by GreenLunar** [comment]
Do most popular messengers (free and proprietary) ship Emoji support by default?

**Comment by Kev** [comment]
Our current intention is to use Unicode emoji, but I've made a note of this in case we decide to use graphics instead. Thanks.
