### ISSUE TITLE
Your package signing keys are expired.

### ISSUE THREAD

**Issue by poetaster** [swift/swift#131]
https://swift.im/keys/packages.key 

pub   rsa4096 2015-11-11 [SC] [expired: 2019-11-28]
      0C4D 5A25 DBEF 212D 7E4F  BC4D 3A95 CBB2 E072 AA5E
uid           [ expired] Swift Package Maintainer <packages@swift.im>

Which blocks use of:
deb https://swift.im/packages/ubuntu/xenial release main

**Comment by theTaikun** [comment]
Duplicate of #120
