### ISSUE TITLE
Swift 6.0

### ISSUE THREAD

**Issue by Neustradamus** [swift/swift#135]
Dear @swift team,

In new Isode M-Link announcement, there is a point about Swift 6.0.

"Provides HTTP Upload (XEP-0363) that enables a client to upload a file to the M-Link server and then share using URL.  This is supported by Swift 6.0 to provide file sharing."

I do not see the download link and source too.

Thanks in advance.

**Comment by Kev** [comment]
Swift 6 is a web-based Isode product that isn't currently open sourced.
