### ISSUE TITLE
[Feature] OMEMO Multi-End Message and Object Encryption

### ISSUE THREAD

**Issue by piwats** [swift/swift#15]
Hello,

would it be possible to get OMEMO in Swift?

http://conversations.im/omemo/
http://conversations.im/xeps/multi-end.html

Thanks in advance.

**Comment by Kev** [comment]
Hi,
Thanks for the idea. We're aware of OMEMO, and it's possible that we'll add support at some point in the future, but it's not on the immediate roadmap (although I imagine we'd welcome a suitable patch, if someone was to produce one).
