### ISSUE TITLE
AppData

### ISSUE THREAD

**Issue by GreenLunar** [swift/swift#29]
Please consider writing and installing an AppData file with the application description and some screenshots, else Swift does not look good in the GNOME and KDE Software Centers. They would love to showcase more applications, but without the extra data file they can't.

See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

---

Perhaps you should generate a POT file, in addition to TS file, for `swift.desktop` and `swift.appdata`.

You might want to look into
https://github.com/QupZilla/qupzilla/pull/1705#issuecomment-140051016
https://github.com/gottcode/focuswriter/blob/master/resources/unix/po/update-po.sh

**Comment by Kev** [comment]
Thanks. Sorting out an AppData file is already on our list, so I hope we'll get to this before too long :)

**Comment by GreenLunar** [comment]
Why did you close this issue, then?

**Comment by Kev** [comment]
GitHub isn't our main tracker (which isn't public), so once something's in our tracker we close the GitHub tickets. Then anything open in GitHub is something that needs our attention.
