### ISSUE TITLE
Swift does not remember conversation window size on macOS

### ISSUE THREAD

**Issue by smammy** [swift/swift#35]
Steps to replicate:
1. Double-click a contact in the roster
2. Resize the conversation window at opens
3. Close the conversation windows
4. Double-click on the same contact again

Expected result:
Conversation window that opens is the *new* size.

Actual result:
Conversation window that opens is the *original* size.

Environment:
- Swift 4.0beta2 built/running with Qt 5.4.2
- macOS 10.11.6

**Comment by Kev** [comment]
Thanks for the report. I can't reproduce this with 4.0beta2-dev112, so I'm assuming it'll be gone for you on the next 4.0 preview.
