### ISSUE TITLE
Bosh error with inner XML causes reconnect loop

### ISSUE THREAD

**Issue by SamWhited** [swift/swift#38]
When logging in over BOSH if the server returns an error to the initial request:

```
<!-- OUT 2017-01-25T16:14:14 -->
POST /http-bind HTTP/1.1
Host: localhost:5280
Content-Type: text/xml; charset=utf-8
Content-Length: 213

<body content='text/xml; charset=utf-8' hold='1' to='localhost' rid='1776361685694531' ver='1.6' wait='60' xml:lang='en' xmlns:xmpp='urn:xmpp:bosh' xmpp:version='1.0' xmlns='http://jabber.org/protocol/httpbind' />
<!-- IN 2017-01-25T16:14:14 -->
HTTP/1.1 200 OK
X-Content-Type-Options: nosniff
Date: Wed, 25 Jan 2017 22:14:14 GMT
Content-Length: 98
Content-Type: text/html; charset=utf-8

<body xmlns="http://jabber.org/protocol/httpbind" condition="bad-request" type="terminate"></body>
```

Swift shows "Error while receiving server data" under the "Connect" button. However, if instead the server sends back an error with some inner XML, for example:

```
<body xmlns="http://jabber.org/protocol/httpbind" condition="bad-request" type="terminate"><text>an error message</text></body>
```

Swift acts as if it has connected (Contacts, Chat, and Notices tabs become available) and enters a reconnect loop, attempting to connect to bosh over and over again (and continuing to receive the error message with the payload). To break the reconnect loop, I hav to go to the "Actions" menu and click "Signout" (even though I was not actually signed in). I would expect both situations to result in the same behavior.

**Comment by Kev** [comment]
Thanks Sam. Yes, I'd expect similar behaviour too. I've filed this internally.
