### ISSUE TITLE
Multi account support ?

### ISSUE THREAD

**Issue by pasnox** [swift/swift#39]
I have 2 jabber accounts (work and personal) and I would prefer Swift to be able to connect to both in the same time.
Is this supported ? planned ?

Thanks for this great xmpp software!

**Comment by er-vin** [comment]
I agree, I would definitely need this as well.

**Comment by wkumari** [comment]
Yup -- this is what is stopping me converting to using Swift.

**Comment by Kev** [comment]
Thanks. This is very much on the list of things we want to do and are tracking, but isn't currently scheduled. We're hoping we might get a student to work on it as part of GSoC this year.

**Comment by pasnox** [comment]
And how you expect to track this enhancement done if you just close it (ie, rejected or done) ?

**Comment by Kev** [comment]
We use an internal issue tracker for our roadmap planning. The github one is just a convenience for people getting us to file stuff there. Don't worry, it's not something we're going to accidentally forget!

**Comment by pasnox** [comment]
I see, thanks ;)
