### ISSUE TITLE
4.0 beta - No way to word wrap text content

### ISSUE THREAD

**Issue by pasnox** [swift/swift#41]
There is no way to word wrap the content and I constantly need to horizontally scroll to read the text, boring :)
Please fix it.

**Comment by Kev** [comment]
Hi. Which beta version are you talking about? The first had an issue with scrolling. Current trunk shouldn't scroll, and I think that fix was included in beta2.

**Comment by pasnox** [comment]
This is what say the about dialog:

Version 4.0beta2

Built with Qt 5.4.2
Running with Qt 5.4.2

**Comment by Kev** [comment]
Thanks. Could you screenshot an example of the wrapping, please?

**Comment by Kev** [comment]
Nevermind, this has been fixed since beta2 and'll be in the next release. Thanks for the report.

**Comment by pasnox** [comment]
Here is it


![screen shot 2017-03-03 at 15 34 11](https://cloud.githubusercontent.com/assets/858201/23555034/a4ea96f6-0027-11e7-802a-043010bfae65.png)

**Comment by Kev** [comment]
Thanks. Yes, that one's definitely fixed.

**Comment by pasnox** [comment]
Great, thanks.
