### ISSUE TITLE
InstallDependecies.sh does not support Linux Mint

### ISSUE THREAD

**Issue by barun511** [swift/swift#43]
As mentioned, the shell script when run from a Linux Mint system returns "Unsupported Linux Distribution". However, this should not happen, since Mint is a Ubuntu based distribution. 

I coded up the fix, but I'm not sure as to how Swift prefers it's workflow. Would you like a pullrequest, or a patch?

**Comment by tfar** [comment]
Yes, a pull request would work just fine.

**Comment by barun511** [comment]
There we go :)
