### ISSUE TITLE
Account context menu shows checkboxes instead of radio buttons [4.0beta2-dev162]

### ISSUE THREAD

**Issue by ge0rg** [swift/swift#47]
When clicking on my nickname / JID, there is a context menu showing:

* [X] Show Nickname
* [ ] Show Address
* Edit Profile

The checkboxes imply that you can have both, but whatever I tap on, exactly one of them is enabled in the end.

Radio buttons would be a better UI for this - or alternatively, just allow the user to show both and let them sort out the width issue. ;)

**Comment by Kev** [comment]
In an ideal world, maybe it'd be radio icons, but Qt doesn't (AFAIK) let us do that, so we've got exclusive checkboxes instead. I don't think we're going to spend time on this one, sorry.

**Comment by ge0rg** [comment]
What about making them behave like proper checkboxes then? I'm sure it would be a minor fix (or maybe even result in less code than now) to allow the nickname+address combination.
