### ISSUE TITLE
'UNREAD' marker not progressed by messages from other client [4.0beta2-dev162]

### ISSUE THREAD

**Issue by ge0rg** [swift/swift#48]
When I write a MUC message from another client with Multi-Session Nicks, the 'UNREAD' marker remains in place. It should be advanced to after the message from the other client, as it is reasonable to assume I've read the MUC content before sending a message.

There are some subtle race conditions here, but generally this should work out sufficiently well.

**Comment by Kev** [comment]
Adding read synchronisation between clients is on the roadmap, thanks.
