### ISSUE TITLE
Start Chat: Set Reason as room name [4.0beta2-dev162]

### ISSUE THREAD

**Issue by ge0rg** [swift/swift#49]
When creating an instant room (Start Chat, add multiple people), there is an option to add a reason text. This seems to not be used in any way.

Please set this reason as the ["identity name"](https://xmpp.org/extensions/xep-0045.html#disco-roominfo) of the newly-created MUC, and use that for display. That will allow other clients to perform a disco#info on the room, and use that text as the "room name" in the UI.

**Comment by ge0rg** [comment]
Minor nitpick: room names are created as UUIDs right now. UUIDs are not the most space-efficient way to encode entropy into the node-part of a JID, and it would be great to utilize e.g. base36 to achieve a shorter JID, to help users without a modern client that would hide an ad-hoc MUC's JID.

**Comment by Kev** [comment]
I think subject might work better than name, but I'll file a ticket to either use the field or hide it, thanks.

**Comment by ge0rg** [comment]
Subject might be a better equivalent for an "invitation reason", but I'd really like to establish the identity name of the MUC as a useful element to display in clients, similar to a contact name in the roster.

Maybe it would be better to rename "Reason" to "room name", or actually to provide both. This is up to your UX department ;)
