### ISSUE TITLE
Incorrect Handling of Daylight Saving Time [4.0beta2-dev162]

### ISSUE THREAD

**Issue by ge0rg** [swift/swift#55]
When Swift is running during a DST switchover, its internal timers get confused and it incorrectly displays day change events:

![Swift DST day-changed](https://cloud.githubusercontent.com/assets/165635/24348429/faccce74-12db-11e7-8962-7cd6905cff75.png)

Please consider adding code to update internal timers on clock changes.

**Comment by tfar** [comment]
Thanks for reporting. I created an internal ticket for this and it will be fixed in the future.
