### ISSUE TITLE
Improve display of /me command according to XEP-0245

### ISSUE THREAD

**Issue by ge0rg** [swift/swift#56]
From XEP-0245:

> It is RECOMMENDED for the client to show the receiving client's understanding of the sender's user name, nickname, or handle [2] followed by the verb phrase in italicized text, prepended by the "*" character.

However, Swift merely displays the text like this (in italics, surrounded with "*"):

*\*does an action**

Please reformat it to the following instead ("* " + nickname + text, all in italics):

*\* Nickname does a action*

**Comment by Kev** [comment]
I think we do what 245 needs already. You get the nickname first, followed by the text in italics prepended by the * character, pretty much exactly what 245 says.
```
Kev
* *does something* *
```
(I guess markdown's probably going to stop that rendering nicely)

**Comment by ge0rg** [comment]
The wording in 0245 is really ambiguous in that regard, but the usual reading, as implemented by most IRC and XMPP clients, is to actually do

    * $nickname $text

Besides, when a /me message follows a normal message from the same person, Swift violates the word of 0245 because the nickname doesn't prepend the /me message anymore. Example:

> Kev
> normal message
> *\*does something**

This one is really all about convention ;-)
