### ISSUE TITLE
Building on Windows 10

### ISSUE THREAD

**Issue by slackr31337** [swift/swift#57]
Hello,

I'm new to Swift and I'm trying to build on Windows 10 with VS2013, Python 2.7.13 and Qt 5.8. It seems that I can build everything except Swift. When I run "scons Swift" it it not added to the "Projects:" list and doesn't build the exe under Swift/QtUI/. I must be missing something? I've tried Swift 3.0, 4.0beta2 and the git master with the same results.

c:\dev\swift-master>scons Swift
scons: Reading SConscript files ...
Checking whether the C++ compiler works... (cached) yes
Checking whether the C compiler works... (cached) yes
Checking whether the C++ compiler supports C++11... (cached) yes
Checking for C library z... (cached) no
Checking for C library resolv... (cached) no
Checking for C library dl... (cached) no
Checking for C library m... (cached) no
Checking for C library c... (cached) no
Checking for C++ library stdc++... (cached) no
Checking for C++ header file boost/signals2.hpp... (cached) no
Checking for C header file libxml/parser.h... (cached) no
Checking for C header file libxml/parser.h... (cached) no
Checking for C header file expat.h... (cached) no
Expat or LibXML not found. Using bundled Expat
Checking for C header file idna.h... (cached) no
Checking for C header file miniupnpc.h... (cached) no
Checking for C header file natpmp.h... (cached) no
Checking for C++ library liblua... (cached) no
Checking for C library libedit... (cached) no
Checking for C header file avahi-client/client.h... (cached) no
Checking for C++ header file hunspell/hunspell.hxx... (cached) no
Checking for C header file dns_sd.h... (cached) no
Bonjour missing. Not building Slimber.
Checking for C function memmove()... (cached) yes
Checking for C function strcasecmp()... (cached) no
Checking for C function stricmp()... (cached) yes
Checking for C function strncasecmp()... (cached) no
Checking for C function strnicmp()... (cached) yes
Warning: 'NoneType' object has no attribute 'group'

  Build Configuration
  -------------------
  Projects: Limber Sluift Swiften

  XML Parsers: Expat (Bundled)
  TLS Support: Schannel
  DNSSD Support: Disabled

scons: done reading SConscript files.
scons: Building targets ...
  GEN Swift\Controllers\BuildVersion.h
  CXX Swift\Controllers\MainController.obj
MainController.cpp
  AR Swift\Controllers\SwiftControllers.lib
scons: done building targets.

**Comment by Kev** [comment]
Hi, I think this suggests that neither Qt nor Git are in your $PATH

**Comment by slackr31337** [comment]
Hi Kev,

I do have Qt and GIT in the %PATH%. 

Here is my config.py

qt = "c:\\dev\\Qt\\5.8\\msvc2013_64"
vcredist = "C:\\Program Files (x86)\\Common Files\\Merge Modules\\vcredist_x86.exe"
wix_bindir = "C:\\Program Files (x86)\\WiX Toolset v3.10\\bin"

**Comment by boring32** [comment]
Hi slackr31337
I think that \ is an escape character for literals in python.
Try with qt="C:\\dev\\Qt\\5.8\\msvc2013_64"

**Comment by Kev** [comment]
Indeed, you'll need to escape the paths in config.py

**Comment by slackr31337** [comment]
Thanks for the response guys. I updated my config.py and I'm seeing the same results. No Swift.exe is being built in the Swift\QtUI directory

qt = "c:\\dev\\Qt\\5.8\\msvc2015"

c:\dev\swift-3.0>scons.bat Swift
scons: Reading SConscript files ...
Checking whether the C++ compiler works... (cached) yes
Checking whether the C compiler works... (cached) yes
Checking for C library z... (cached) no
Checking for C library resolv... (cached) no
Checking for C library dl... (cached) no
Checking for C library m... (cached) no
Checking for C library c... (cached) no
Checking for C++ library stdc++... (cached) no
Checking for C++ header file boost/signals.hpp... (cached) no
Checking for C header file libxml/parser.h... (cached) no
Checking for C header file libxml/parser.h... (cached) no
Checking for C header file expat.h... (cached) no
Expat or LibXML not found. Using bundled Expat
Checking for C header file idna.h... (cached) no
Checking for C header file miniupnpc.h... (cached) no
Checking for C header file natpmp.h... (cached) no
Checking for C++ library liblua... (cached) no
Checking for C library libedit... (cached) no
Checking for C header file avahi-client/client.h... (cached) no
Checking for C header file openssl/ssl.h... (cached) no
Checking for C header file dns_sd.h... (cached) no
Bonjour missing. Not building Slimber.
Checking for C function memmove()... (cached) yes
Checking for C function strcasecmp()... (cached) no
Checking for C function stricmp()... (cached) yes
Checking for C function strncasecmp()... (cached) no
Checking for C function strnicmp()... (cached) yes
Warning: 'NoneType' object has no attribute 'group'

  Build Configuration
  -------------------
  Projects: Limber Sluift Swiften

  XML Parsers: Expat (Bundled)
  TLS Support: Schannel
  DNSSD Support: Disabled

scons: done reading SConscript files.
scons: Building targets ...
scons: `Swift' is up to date.
scons: done building targets.

I've tried starting with a clean Swift-3.0 source and upgrading to VC 2015. I've got to be missing something. I also using the pre-built QT libs. Should I try using the QT 5.8 source?

Thanks,
Robert

**Comment by Kev** [comment]
I would first try with latest master, with no config.py, making sure both git and the Qt tools are in the path. When that doesn't work, can you share the failure from config.py, please?

**Comment by slackr31337** [comment]
Thanks Kev. The latest master works just fine. I was able to compile and run Swift.exe

**Comment by Kev** [comment]
Thanks for reporting back.
