### ISSUE TITLE
line break missing

### ISSUE THREAD

**Issue by miczac** [swift/swift#58]
Hi, am I missing something, is it just me or is this hard to read?

![screen shot 2017-04-10 at 13 56 06](https://cloud.githubusercontent.com/assets/1922103/24860765/70375614-1df6-11e7-90a1-6d197e68026a.png)

This is on OS X 10.9.5. swift / jolly brisk 4.0 beta 2

**Comment by Kev** [comment]
Hi, the horizontal scrollbars are a bug that's since been fixed. It'll be ok in the 4.0 RC when we release that. Thanks for the report.
