### ISSUE TITLE
Bundles vulnerable copy of Expat - please update to 2.2.1

### ISSUE THREAD

**Issue by hartwork** [swift/swift#70]
Hi!

This repository [bundles an outdated vulnerable copy of Expat 2.1.0](https://github.com/swift/swift/tree/master/3rdParty/Expat/src). Please update your copy to version 2.2.1 with the latest security fixes. A change log with details is available at https://github.com/libexpat/libexpat/blob/master/expat/Changes . Thank you!

Best

&nbsp;
Sebastian

**Comment by tfar** [comment]
Thanks. Will look into it.

**Comment by tfar** [comment]
Fixed with a507a88a189bb603c9f2d686c9c8dafca49c053d .
