### ISSUE TITLE
ALT+L should not trigger layout menu

### ISSUE THREAD

**Issue by wiktor-k** [swift/swift#81]
Hello,

When pressing `ALT+L` on the conversation window the layout menu is shown. Unfortunately this shortcut is used to input specific Polish character (**ł**) and that makes the conversation really hard.

Is it possible to unset or remove this shortcut? Swift has great design as it is and I don't want to change it anyway...

I'm using **Swift 4.0rc2** on **Windows 10**.

**Comment by Kev** [comment]
Thanks. We'll remove that shortcut.

**Comment by Kev** [comment]
This has been removed.
