### ISSUE TITLE
Additional Preferences UI

### ISSUE THREAD

**Issue by jwhipp** [swift/swift#90]
I am not seeing a preference screen allowing for the adjustment of the following things:

- Away/Idle time
- Color schemes
- Fonts
- Layouts
- Icons (example egg shape to circle)

Is this planned for the future? Just about ever other XMPP client has these as configurable options.

**Comment by Kev** [comment]
Thanks for the question. Although 4.0 has a new chat theme, we're not currently intending making this configurable. It does add a 'trellis view' letting you see multiple chat windows at once, if that was what you were hoping for with changing the layout. Icons and away/idle times we're also not currently intending making configurable. Swift follows a philosophy of trying to minimise the number of choices facing users, so at the moment we're not planning on exposing configuration for these.

**Comment by jwhipp** [comment]
I totally get making auto configurable to work for most situations but this is going to cause issues for users especially when it comes to things like time outs, idle, and priority which you don't expose.

https://jabber.at/p/clients/?os=win

Swift is missing a few XEPs from this list, one of those is the priority configuration issue.
