### ISSUE TITLE
XEP-0313: MAM MUC does not appear to work

### ISSUE THREAD

**Issue by devurandom** [swift/swift#93]
My server is running Prosody 0.10.0 with mod_mam_muc enabled for the MUC component. The MySQL database backing Prosody contains archives for the chat-room, but Swift does not show these archives when joining the room or scrolling upwards in the chat window.

Swift is at version 5.0alpha-dev14.

**Comment by tfar** [comment]
Swift does not support MAM yet. However it is on our roadmap.
