### ISSUE TITLE
swift-im 4.0rc2 runs in english

### ISSUE THREAD

**Issue by Fisiu** [swift/swift#95]
My current locale is:
```bash
fisiu@pendrak:~ $ localectl status
   System Locale: LC_CTYPE=pl_PL.UTF-8
       VC Keymap: pl
      X11 Layout: pl
       X11 Model: microsoftpro
     X11 Options: terminate:ctrl_alt_bksp
```

However, when I run swift-im, interface is in English but it should load system one.
![screenshot_20171019_231120](https://user-images.githubusercontent.com/33876/31794622-3b4c39a0-b523-11e7-9ed3-d25c2863b8cd.png)

**Comment by tfar** [comment]
Where did you get Swift from? If compiled yourself, what Qt version do you build against (info can be found in the help menu)?

**Comment by Fisiu** [comment]
I built rpm package for openSUSE:
https://build.opensuse.org/package/show/home:Fisiu:branches:network/swift-im

Qt 5.9.1 was used in my case.

**Comment by tfar** [comment]
@jubalh do you also see this issue on OpenSUSE?

**Comment by jubalh** [comment]
@tfar works perfectly fine:
![show-swift-de](https://user-images.githubusercontent.com/1658215/36785706-0116180a-1c84-11e8-98e4-d88175063e33.png)

@Fisiu did you set the locale in YaST?
`yast -> language -> primary language`

I'm using `network/swift-im` which is also in TW.

**Comment by Fisiu** [comment]
It looks like I already fixed a package: https://build.opensuse.org/request/show/536224
And it works fine on Tumbleweed.

**Comment by jubalh** [comment]
I will review them in the next days

**Comment by jubalh** [comment]
@Fisiu not really sure what you mean. You submitted that change 4 months ago? What bug did you hit now and how was it solved?

**Comment by Fisiu** [comment]
@jubalh Back in October last year, openSUSE package was broken and translation of swift-im was not provided. I thought it was issue with swift-im itself, so I opened this ticket. In the meantime I digged around and fixed package to provide translations. Then I forgot about this ticket.

I closed this ticket, because it's no longer valid.

**Comment by jubalh** [comment]
Right, only now saw that this is an old ticket.
